#!/usr/bin/env bash
# this alias is so that I can ignore errors on this
stop_firmware() {
  echo stop | sudo tee ${PRU0}/state > /dev/null 2> /dev/null
}
echo "Starting GPIO setup"
scripts/pin-config > /dev/null 2> /dev/null
PRU0=/sys/class/remoteproc/remoteproc1
TARGET=gen/ledscape.out

while [[ ! -f ${PRU0}/state ]]
do
  echo "Waiting for PRU…"
  sleep 0.75
done

if [[ -e /tmp/ledscape_deployed ]]
then
  echo "LEDScape already deployed"
else
echo "Stopping any running PRU firmware"
stop_firmware || true # the || true is to ignore errors
echo "Deploying LEDScape firmware"
cp ${TARGET} /lib/firmware/am335x-pru0-fw
echo "Starting LEDScape firmware"
echo am335x-pru0-fw | sudo tee ${PRU0}/firmware > /dev/null 2> /dev/null
echo start | sudo tee ${PRU0}/state > /dev/null
fi
touch /tmp/ledscape_deployed

# run any commands within the launcher context
if [[ "$#" -gt 0 ]]
then
  echo "Launching client '$@'"
  sudo "$@"
fi