# Build the LEDScape library

LIB-y += libledscape.a
BIN-y += pru_status
BIN-y += mem_scanner

libledscape.srcs += \
	ledstrips.c \
	lut.c \

pru_status.srcs += pru_status.c
mem_scanner.srcs += mem_scanner.c

include ../../Makefile.common