#!/usr/bin/env bash

sudo apt-get remove -y bb-node-red-installer --allow-change-held-packages
sudo apt-get remove -y c9-core-installer --allow-change-held-packages

sudo python3 -m pip install zeroconf

cd ../services
sudo systemctl enable throwingzero.service 
sudo systemctl start throwingzero.service