#!/usr/bin/env bash
kern=`uname -r`
echo "Your kernel is ${kern}. This installer works for 4.19 kernels."
read -p "Press [Enter] to provision this Bagelbox for network rendering."
echo "What hostname would you like this Bagelbox to use? (leave blank to leave unchanged) "
read -p "[HOST] > "  hostval
echo "What is the LED config as:"
read -p "[WIDTH](Max: 32) > " w
read -p "[HEIGHT](Max: 512) > " h
read -p "[BYTES](RGB:3, RGBW:4) > " b

if [[ $w -gt 32 ]]
then
  echo "Too many channels- 32 is the max. No changes have been made."
  exit
fi

case $b in
  3)
    ;;
  4)
    ;;
  *)
    echo "Num bytes must be 3 or 4 (RGB or RGBW). No changes have been made."
    exit
    ;;
esac

if [[ $h -gt 512 ]]
then
  echo "Too many leds per channel- 512 is the max. No changes have beeen made."
  exit
fi

if [[ -z $hostval ]]
then
  echo "You didn't supply a host name. Not setting one. Re-run provision.sh or change the hostname yourself."
else
  echo "Setting hostname to $hostval."
  echo $hostval | sudo tee /etc/hostname
  sudo sed -i.bak "s/localhost/localhost $hostval/" /etc/hosts
fi

if [[ -z $w ]] || [[ -z $h ]] || [[ -z $b ]]
then
  echo "You didn't supply all LEDs dimensions. Not setting config. Run provision.sh again, or change the leds.config file yourself."
else
  echo "Setting leds.config to $w,$h,$b"
  echo "$w,$h,$b" > leds.config
fi
