#!/usr/bin/env bash
kern=`uname -r`
echo "Your kernel is ${kern}. This installer works for 4.19 kernels."
read -p "Press [Enter] to provision this Bagelbox for network rendering."
echo "What hostname would you like this Bagelbox to use? "
read -p "[HOST] > "  hostval
echo "What is the LED config as:"
read -p "[WIDTH] > " w
read -p "[HEIGHT] > " h
read -p "[BYTES] > " b

if [[ $w -gt 32 ]]
then
  echo "Too many channels- 32 is the max. No changes have been made."
  exit
fi

case $b in
  3)
    ;;
  4)
    ;;
  *)
    echo "Num bytes must be 3 or 4 (RGB or RGBW). No changes have been made."
    exit
    ;;
esac

if [[ $h -gt 512 ]]
then
  echo "Too many leds per channel- 512 is thee max. No changes have beeen made."
  exit
fi

if [[ -z $hostval ]]
then
  echo "You didn't supply a host name. Not setting one. Re-run provision.sh or change the hostname yourself."
else
  echo "Setting hostname to $hostval."
  echo $hostval | sudo tee /etc/hostname
  sudo sed -i.bak "s/localhost/localhost $hostval/" /etc/hosts
fi

if [[ -z $w ]] || [[ -z $h ]] || [[ -z $b ]]
then
  echo "You didn't supply all LEDs dimensions. Not setting config. Run provision.sh again, or change the leds.config file yourself."
else
  echo "Setting leds.config to $w,$h,$b"
  echo "$w,$h,$b" > leds.config
fi

echo "Installing the bagel uBoot config."
sudo sed -i.bak "s/#disable_uboot_overlay_video=1/disable_uboot_overlay_video=1/g" /boot/uEnv.txt
sudo sed -i.bak "s/#disable_uboot_overlay_audio=1/disable_uboot_overlay_audio=1/g" /boot/uEnv.txt

echo "Updating the device tree."
sudo cp dts/*.dtbo /lib/firmware

echo "This script assumes that your uEnv.txt enables the PRU, which should be the default. Ensure that a uboot_overlay_pru is set."
echo "If not, manually change it."

echo "Installing services"
sudo scripts/setup_services

echo "Throwing Bagels has been installed. Services are installed, but not enabled. Check the READMe for more."
echo "Please reboot before trying the included software."
echo "After a reboot, you can use systemctl to enable/start either multidemo or led-udp"
